<Project>
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<LangVersion>latest</LangVersion>
		<AnalysisMode>All</AnalysisMode>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Instrumented' Or '$(RegexInstrumentation)' == 'true'">
		<DefineConstants>$(DefineConstants);REGEX_INSTRUMENTATION</DefineConstants>
		<Optimize>true</Optimize>
	</PropertyGroup>
</Project>